### ISSUE TITLE
rendered component

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/code-block#11]
```ftd
-- rendered: 
body input: 
ftd.ui list output:
optional string filename:	
```

Ex.
```ftd
-- rendered:

\-- ftd.text: Hello world

-- rendred.output:

-- ftd.text: Hello world

-- end: rendred.output

```

**Comment by gsalunke** [comment]
@amitu 
Fixed this issue adding `rendered` component into `code-block`

https://github.com/FifthTry/code-block/commit/23f037442a266b9f864b93e1989e56441a96e443

[See it in action](https://fifthtry.github.io/code-block/)

**Comment by amitu** [comment]
@gsalunke just noting down the problem lest we forget it: the position of copy and download buttons that come up on hover in the source code area of the rendered component is a bit too close to the top, and should be like how it is for other code blocks.

**Comment by gsalunke** [comment]
> @gsalunke just noting down the problem lest we forget it: the position of copy and download buttons that come up on hover in the source code area of the rendered component is a bit too close to the top, and should be like how it is for other code blocks.

@amitu 
This is fixed. with our new release. https://fifthtry.github.io/code-block/

Closing this issue.
